flowchart LR
    node_0[products]
    node_1[id]
    node_2[name]
    node_3[price]
    node_4[FROM]
    node_5[WHERE]
    node_6[SELECT]
    node_0 --> node_1
    node_0 --> node_2
    node_0 --> node_3
    node_0 --> node_4
    node_4 --> node_5
    node_5 --> node_6