flowchart LR
    node_0["FROM<br/>---<br/>products.id<br/>products.name<br/>products.price"]
    node_1["WHERE<br/>---<br/>price &gt; 50"]
    node_2["SELECT<br/>---<br/>name<br/>price"]
    node_0 --> node_1
    node_1 --> node_2