flowchart LR
    node_0[FROM orders]
    node_1["WHERE<br/>---<br/>amount &gt; expr"]
    subgraph subquery_node_2 ["Subquery (scalar)"]
        direction TB
        subq_0_node_0[FROM orders]
        subq_0_node_1["WHERE<br/>---<br/>customer_id IN expr"]
        subgraph subquery_subq_0_node_2 ["Subquery (in)"]
            direction TB
            subq_1_node_0[FROM customers]
            subq_1_node_1["WHERE<br/>---<br/>country = 'JP'"]
            subq_1_node_2["SELECT id"]
            subq_1_node_0 --> subq_1_node_1
            subq_1_node_1 --> subq_1_node_2
        end
        subq_1_node_2 -->|expr| subq_0_node_1
        subq_0_node_3["SELECT AVG(amount)"]
        subq_0_node_0 --> subq_0_node_1
        subq_0_node_1 --> subq_0_node_3
    end
    subq_0_node_3 -->|expr| node_1
    node_3["SELECT<br/>---<br/>*"]
    node_0 --> node_1
    node_1 --> node_3