flowchart LR
    node_0[customers AS c]
    node_1[FROM customers AS c]
    node_2["WHERE EXISTS(subquery)"]
    node_3[["Subquery (exists)"]]
    node_4["SELECT c.customer_id, c.name"]
    node_0 --> node_1
    node_1 --> node_2
    node_3 -->|exists| node_2
    node_2 --> node_4