flowchart LR
    node_0[FROM users]
    node_1["SELECT<br/>---<br/>id<br/>name<br/>user AS source"]
    node_2["UNION ALL<br/>---<br/>id<br/>name<br/>source"]
    node_3[FROM organizations]
    node_4["SELECT<br/>---<br/>id<br/>company_name AS name<br/>org AS source"]
    node_0 --> node_1
    node_1 --> node_2
    node_3 --> node_4
    node_4 --> node_2